apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: django-py
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-py
  template:
    metadata:
      labels:
        app: django-py
    spec:
      containers:
      - name: web-app
        image: bibichanel/nginx:custom
        ports:
        - containerPort: 80
